In [11]:
!pip install vizdoom

In [11]:
# !cd github & git clone https://github.com/mwydmuch/ViZDoom

The system cannot find the path specified.
Cloning into 'ViZDoom'...
Updating files:   8% (174/2062)
Updating files:   9% (186/2062)
Updating files:  10% (207/2062)
Updating files:  11% (227/2062)
Updating files:  12% (248/2062)
Updating files:  13% (269/2062)
Updating files:  14% (289/2062)
Updating files:  15% (310/2062)
Updating files:  16% (330/2062)
Updating files:  17% (351/2062)
Updating files:  18% (372/2062)
Updating files:  19% (392/2062)
Updating files:  20% (413/2062)
Updating files:  21% (434/2062)
Updating files:  22% (454/2062)
Updating files:  23% (475/2062)
Updating files:  24% (495/2062)
Updating files:  25% (516/2062)
Updating files:  26% (537/2062)
Updating files:  27% (557/2062)
Updating files:  28% (578/2062)
Updating files:  29% (598/2062)
Updating files:  30% (619/2062)
Updating files:  31% (640/2062)
Updating files:  32% (660/2062)
Updating files:  33% (681/2062)
Updating files:  34% (702/2062)
Updating files:  35% (722/2062)
Updating files:  36% (743/2062)
Upd

In [7]:

# Import vizdoom for game env
from vizdoom import * 
# Import random for action sampling
import random
# Import time for sleeping
import time 
# Import numpy for identity matrix
import numpy as np

In [219]:
# Setup game
game = DoomGame()
game.load_config(r'C:\Users\indug\doom\ViZDoom\scenarios\defend_the_center.cfg')
game.init()

In [14]:
# This is the set of actions we can take in the environment
actions = np.identity(3, dtype=np.uint8)

In [15]:
state = game.get_state()

In [16]:
state.game_variables

array([ 26., 100.])

In [220]:
# Loop through episodes 
episodes = 10 
for episode in range(episodes): 
    # Create a new episode or game 
    game.new_episode()
    # Check the game isn't done 
    while not game.is_episode_finished(): 
        # Get the game state 
        state = game.get_state()
        # Get the game image 
        img = state.screen_buffer
        # Get the game variables - ammo
        info = state.game_variables
        # Take an action
        reward = game.make_action(random.choice(actions),4)
        # Print rewward 
        print('reward:', reward) 
        time.sleep(0.02)
    print('Result:', game.get_total_reward())
    time.sleep(2)

reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 1.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
reward: 0.0
rewa

KeyboardInterrupt: 

In [18]:
game.close()

In [138]:
!pip install gym

In [10]:
# Import environment base class from OpenAI Gym
from gym import Env
# Import gym spaces 
from gym.spaces import Discrete, Box
# Import opencv 
import cv2

In [11]:
# game.get_state().screen_buffer.shape

In [12]:
# Create Vizdoom OpenAI Gym Environment
class VizDoomGym(Env): 
    # Function that is called when we start the env
    def __init__(self, render=False): 
        # Inherit from Env
        super().__init__()
        # Setup the game 
        self.game = DoomGame()
        self.game.load_config(r'C:\Users\indug\doom\ViZDoom\scenarios\defend_the_center.cfg')
        
        # Render frame logic
        if render == False: 
            self.game.set_window_visible(False)
        else:
            self.game.set_window_visible(True)
        
        # Start the game 
        self.game.init()
        
        # Create the action space and observation space
        self.observation_space = Box(low=0, high=255, shape=(100,160,1), dtype=np.uint8) 
        self.action_space = Discrete(3)
        
    # This is how we take a step in the environment
    def step(self, action):
        # Specify action and take step 
        actions = np.identity(3)
        reward = self.game.make_action(actions[action], 4) 
        
        # Get all the other stuff we need to retun 
        if self.game.get_state(): 
            state = self.game.get_state().screen_buffer
            state = self.grayscale(state)
            ammo = self.game.get_state().game_variables[0]
            info = ammo
        else: 
            state = np.zeros(self.observation_space.shape)
            info = 0 
        
        info = {"info":info}
        done = self.game.is_episode_finished()
        
        return state, reward, done, info 
    
    # Define how to render the game or environment 
    def render(): 
        pass
    
    # What happens when we start a new game 
    def reset(self): 
        self.game.new_episode()
        state = self.game.get_state().screen_buffer
        return self.grayscale(state)
    
    # Grayscale the game frame and resize it 
    def grayscale(self, observation):
        gray = cv2.cvtColor(np.moveaxis(observation, 0, -1), cv2.COLOR_BGR2GRAY)
        resize = cv2.resize(gray, (160,100), interpolation=cv2.INTER_CUBIC)
        state = np.reshape(resize, (100,160,1))
        return state
    
    # Call to close down the game
    def close(self): 
        self.game.close()

In [24]:
env = VizDoomGym(render=True)

In [41]:
# env.step(2)

In [42]:
state = env.reset()

In [145]:
env.reset()

array([[[55],
        [50],
        [59],
        ...,
        [57],
        [57],
        [66]],

       [[68],
        [65],
        [65],
        ...,
        [56],
        [67],
        [72]],

       [[49],
        [79],
        [66],
        ...,
        [79],
        [51],
        [29]],

       ...,

       [[75],
        [63],
        [62],
        ...,
        [44],
        [71],
        [60]],

       [[15],
        [48],
        [47],
        ...,
        [49],
        [69],
        [47]],

       [[22],
        [14],
        [26],
        ...,
        [57],
        [37],
        [39]]], dtype=uint8)

In [43]:
env.close()

In [44]:
# Import Environment checker
from stable_baselines3.common import env_checker

In [148]:
# env_checker.check_env(env)

In [149]:

# !pip install matplotlib

In [150]:
# from matplotlib import pyplot as plt

In [151]:

# plt.imshow(cv2.cvtColor(state, cv2.COLOR_BGR2RGB))

In [17]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121


In [45]:
!pip install stable-baselines3[extra]


In [46]:
# Import os for file nav
import os 
# Import callback class from sb3
from stable_baselines3.common.callbacks import BaseCallback

In [47]:
class TrainAndLoggingCallback(BaseCallback):

    def __init__(self, check_freq, save_path, verbose=1):
        super(TrainAndLoggingCallback, self).__init__(verbose)
        self.check_freq = check_freq
        self.save_path = save_path

    def _init_callback(self):
        if self.save_path is not None:
            os.makedirs(self.save_path, exist_ok=True)

    def _on_step(self):
        if self.n_calls % self.check_freq == 0:
            model_path = os.path.join(self.save_path, 'best_model_{}'.format(self.n_calls))
            self.model.save(model_path)

        return True

In [48]:
CHECKPOINT_DIR = './train/train_defend'
LOG_DIR = './logs/log_defend'

In [49]:
callback = TrainAndLoggingCallback(check_freq=10000, save_path=CHECKPOINT_DIR)

In [4]:

# import ppo for training
from stable_baselines3 import PPO

In [52]:
# Non rendered environment
env = VizDoomGym()

In [53]:
model = PPO('CnnPolicy', env, tensorboard_log=LOG_DIR, verbose=1, learning_rate=0.0001, n_steps=2048)


Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


C:\Users\indug\anaconda3\Lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


In [54]:
model.learn(total_timesteps=100000, callback=callback)

Logging to ./logs/log_defend\PPO_1
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 82.2     |
|    ep_rew_mean     | 0.417    |
| time/              |          |
|    fps             | 66       |
|    iterations      | 1        |
|    time_elapsed    | 30       |
|    total_timesteps | 2048     |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 88.4         |
|    ep_rew_mean          | 0.652        |
| time/                   |              |
|    fps                  | 67           |
|    iterations           | 2            |
|    time_elapsed         | 61           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0065003764 |
|    clip_fraction        | 0.0329       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.09        |
|    explained_variance

In [2]:
# Import eval policy to test agent
from stable_baselines3.common.evaluation import evaluate_policy

In [5]:

# Reload model from disc
model = PPO.load('./train/train_defend/best_model_70000')

In [13]:

# Create rendered environment
env = VizDoomGym(render=True)

In [15]:
# Evaluate mean reward for 10 games
mean_reward, _ = evaluate_policy(model, env, n_eval_episodes=50)

In [16]:

mean_reward

20.0

In [ ]:

for episode in range(10): 
    obs = env.reset()
    done = False
    total_reward = 0
    while not done: 
        action, _ = model.predict(obs)
        obs, reward, done, info = env.step(action)
        time.sleep(0.80)
        total_reward += reward
    print('Total Reward for episode {} is {}'.format(episode, total_reward))
    time.sleep(2)

In [225]:
env.close()

In [205]:
env = VizDoomGym(render=True)

In [214]:
env.step(1)

(array([[[ 6],
         [10],
         [ 9],
         ...,
         [ 6],
         [11],
         [ 4]],
 
        [[ 9],
         [ 9],
         [ 6],
         ...,
         [ 6],
         [ 6],
         [ 4]],
 
        [[10],
         [ 7],
         [ 7],
         ...,
         [ 6],
         [ 6],
         [ 9]],
 
        ...,
 
        [[75],
         [63],
         [62],
         ...,
         [44],
         [71],
         [60]],
 
        [[15],
         [48],
         [47],
         ...,
         [49],
         [69],
         [47]],
 
        [[22],
         [14],
         [26],
         ...,
         [57],
         [37],
         [39]]], dtype=uint8),
 0.0,
 False,
 {'info': 26.0})

In [204]:
env.close()